development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ldap_reloaded_development
  pool: 5
  username: root
  password: tuna46
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ldap_reloaded_test
  pool: 5
  username: root
  password: tuna46
  socket: /var/run/mysqld/mysqld.sock
